# Generated by Django 2.1.7 on 2019-04-12 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telecallers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('sscname', models.CharField(max_length=128)),
                ('sscpassyr', models.IntegerField()),
                ('hscname', models.CharField(max_length=256)),
                ('hscpassyr', models.IntegerField()),
                ('diplname', models.CharField(blank=True, max_length=256)),
                ('diplpassyr', models.IntegerField(blank=True)),
                ('degname', models.CharField(max_length=256)),
                ('degpassyr', models.IntegerField()),
                ('masname', models.CharField(blank=True, max_length=256)),
                ('maspassyr', models.IntegerField(blank=True)),
                ('designation', models.CharField(max_length=128)),
                ('passyr', models.IntegerField()),
                ('expyr', models.IntegerField()),
                ('expmon', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
