# Generated by Django 2.1.7 on 2019-04-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telecallers', '0001_initial'),
        ('counselor', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='counselor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='counselor.Counselor'),
        ),
        migrations.AddField(
            model_name='admission',
            name='telecaller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='telecallers.Telecallers'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='counselor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='counselor.Counselor'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='telecaller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='telecallers.Telecallers'),
        ),
        migrations.AddField(
            model_name='telecaller',
            name='telecaller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='telecallers.Telecallers'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='enquiry_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Enquiry'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='telecaller_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Telecaller'),
        ),
    ]
