# Generated by Django 2.1.7 on 2019-04-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20190413_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecaller',
            name='source',
            field=models.CharField(blank=True, choices=[('Banner', 'Banner'), ('Job Fair', 'Job Fair'), ('Friends', 'Friends'), ('Hoardings', 'Hoardings'), ('Seminar', 'Seminar'), ('Ex-Student', 'Ex-Student'), ('Mailer', 'Mailer'), ('Waves Website', 'Waves Website'), ('Email', 'Email'), ('Just Dial', 'Just Dial'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Waves App', 'Waves App'), ('Workshop', 'Workshop')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='telecaller',
            name='generated_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='telecaller',
            name='telecaller',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='telecallers.Telecallers'),
        ),
    ]
