# Generated by Django 2.1.7 on 2019-04-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20190416_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecaller',
            name='telecaller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='telecallers.Telecallers'),
        ),
    ]
